server:
  port: 8080

app:
  jira:
    url: https://finologee.atlassian.net/
  users:
    - slackId: U784J8M51
      jiraId: "557058:d332697f-ed64-413b-a97d-b22bbd1f5c0e"
      id: bse
  scheduler:
    jira-status:
      cron: 0 35 9 * * *
      channelId: CHLBEN2HJ
